### ISSUE TITLE
Can I use this repo to export public channal chats?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Layerex/telegram-export-gifs#1]
Hello:
I have joined about 30 public channels, I want to export 2 of them, the channel chats every day.
I am using Windows 10, and Telegram desktop version 4.0.1, I can export channel chats by hand from Telegram desktop by setting 6 different parameters.
However, this type of job is tedious, I want to know if I can use this repo to make channel chats exporting job as a Python script, so I can call the Python script later on, I don't have to do the job by hand every day.
Please advise: how to provide 6 parameters, so I can use the repo to export one public channel chats.
I think I need to export only 3 types of files: one is the result.json, a json format file indicating chat ID, file type, etc.  Another file is: jpg for video thumbnail, and last file type is .MP4. I think if your repo can export GIF (I think it is made of multiple jpg/png files), then how about adding export .MP4 format file, then it is possible to export channal chats, right?
Thanks,

**Comment by Layerex** [comment]
No, this program exports saved gifs (ones which are near stickers in UI). For exporting chats and channels use https://github.com/3bl3gamer/tg-history-dumper
